server:
  port: 3344
spring:
  application:
    name: config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhangjq-92/springcloud-config.git
          search-paths:
            - springcloud-config
      label: master


eureka:
  client:
    #false表示不向服务注册中心注册自己
    register-with-eureka: true
    #false表示自己就是服务注册中心，不需要去检索服务
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/


